### ISSUE TITLE
Help running this on local dev

### ISSUE THREAD

**Issue by MrSunshyne** [shopyo/pythoncms#335]
## 🐛 Bug Report

I tried running this on my local machine but encountered an issue when I reached this command `shopyo initialise`

## 🔬 How To Reproduce

```
OK python -m pip install -e .

Running setup.py install for shopyo ... done
Running setup.py develop for pythoncms
Successfully installed Flask-2.2.2 Flask-Admin-1.6.0 Flask-Login-0.6.2 Flask-Migrate-4.0.4 Flask-SQLAlchemy-3.0.3 Flask-WTF-1.1.1 SQLAlchemy-1.4.46 WTForms-3.0.1 Werkzeug-2.2.2 alembic-1.9.2 email-validator-1.3.1 flask-mailman-0.3.0 flask-marshmallow-0.14.0 greenlet-2.0.2 itsdangerous-2.1.2 marshmallow-3.19.0 marshmallow-sqlalchemy-0.28.1 mkdocs-material-extensions-1.1.1 pythoncms shopyo-4.8.6

OK cd pythoncms
ERR shopyo initialise
bash: shopyo: command not found...
```

### Environment

* OS: Linux  / Fedora 36
* Python version: Python 3.10.9

### Screenshots
![image](https://user-images.githubusercontent.com/1721611/216774961-2ed9487c-bdcb-4fef-879c-2ad936df26c5.png)

## 📈 Expected behavior
Execute the command correctly and proceed to the next command

**Comment by Abdur-rahmaanJ** [comment]
@MrSunshyne You need to install it in a virtual environment ^^

**Comment by MrSunshyne** [comment]
Could you point me towards some instructions to do that? 
I'm not very versed in python but would still like to try it out 😁

**Comment by Abdur-rahmaanJ** [comment]
@MrSunshyne 

```
python -m venv venv
. ./venv/bin/activate
```

Then continue instructions as usual

**Comment by AndrejGorodnij** [comment]
Algorithm looks like that:

Create virtual environment using:
```
python -m venv venv
. ./venv/bin/activate
```
or

```
virtualenv venv
. ./venv/bin/activate
```
Then run `python -m pip install -e .` that will install needed packages

THEN (IMPORTANT) - `cd pythoncms`

After that - `shopyo initialize`

Final - `flask --debug run`
