### ISSUE TITLE
Add <br> tag

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [shopyo/pythoncms#338]
Add `<br/>` tag to this line

https://github.com/shopyo/pythoncms/blob/4339f7c96ee5c79dc1df2a191b653fe2606feb84/pythoncms/static/themes/back/sneat/base.html#L294

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue.Please assign it to me.

**Comment by Abdur-rahmaanJ** [comment]
@tarunsamanta2k20 Sorry, someone else pred before you. Thanks a lot for volunteering!
